create table if not exists public.tce_balancetes_despesas_orcamentarias (
  id uuid primary key default gen_random_uuid(),
  codigo_municipio text not null,
  exercicio_orcamento text not null,
  data_referencia_doc text not null,
  codigo_orgao text not null,
  codigo_unidade_orcamentaria text not null,
  codigo_funcao text not null,
  codigo_subfuncao text not null,
  codigo_programa text not null,
  codigo_projeto_atividade text not null,
  numero_projeto_atividade text not null,
  numero_subprojeto_atividade text not null,
  codigo_elemento_despesa text not null,
  tipo_balancete text,
  tipo_fonte text,
  codigo_fonte text not null,
  valor_fixado_orcamento numeric(18, 2),
  valor_suplementado_no_mes numeric(18, 2),
  valor_suplementado_ate_mes numeric(18, 2),
  valor_anulacoes_dotacao_ate_mes numeric(18, 2),
  valor_anulacoes_empenhos_no_mes numeric(18, 2),
  valor_anulacoes_empenhos_ate_mes numeric(18, 2),
  valor_empenhado_no_mes numeric(18, 2),
  valor_empenhado_ate_mes numeric(18, 2),
  valor_liquidado_no_mes numeric(18, 2),
  valor_liquidado_ate_mes numeric(18, 2),
  valor_pago_no_mes numeric(18, 2),
  valor_pago_ate_mes numeric(18, 2),
  valor_empenhado_pagar numeric(18, 2),
  valor_estornos_liquidacao_no_mes numeric(18, 2),
  valor_estornos_liquidacao_ate_mes numeric(18, 2),
  valor_estornos_pagos_no_mes numeric(18, 2),
  valor_estornos_pagos_ate_mes numeric(18, 2),
  valor_saldo_dotacao numeric(18, 2),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (
    codigo_municipio,
    exercicio_orcamento,
    data_referencia_doc,
    codigo_orgao,
    codigo_unidade_orcamentaria,
    codigo_funcao,
    codigo_subfuncao,
    codigo_programa,
    codigo_projeto_atividade,
    numero_projeto_atividade,
    numero_subprojeto_atividade,
    codigo_elemento_despesa,
    codigo_fonte
  )
);

create index if not exists idx_tce_bal_despesas_scope
  on public.tce_balancetes_despesas_orcamentarias (codigo_municipio, exercicio_orcamento, data_referencia_doc);

